messages:
  spawn-teleport-message: false
  join-quit-messages: true
  date-format: "dd/MM/yyyy"
settings:
  update-checker: true
  scoreboard: true
  archive-vanish: true
  teleport-after-creation: true
  builder:
    block-worldedit-non-builder: true
    world-edit-wand: "WOODEN_AXE"
    creator-is-builder: false
  navigator:
    item: "CLOCK"
    give-item-on-join: true
world:
  default:
    time:
      sunrise: 0
      noon: 6000
      night: 18000
    worldborder:
      size: 6000000
    difficulty: "PEACEFUL"
    gamerules:
      doDaylightCycle: false
      doMobSpawning: false
      doFireTick: false
    settings:
      physics: true
      explosions: true
      mob-ai: true
      block-breaking: true
      block-placement: true
      block-interactions: true
  lock-weather: true
  import-all:
    delay: 30
  max-amount:
    public: -1
    private: -1
  unload:
    enabled: false
    time-until-unload: "01:00:00"
    blacklisted-worlds:
      - world
      - world_nether
      - worth_the_end
  void-block: true