name: BuildSystem
version: ${version}
api-version: "1.13"
author: einTosti
main: de.eintosti.buildsystem.BuildSystem
description: Powerful, easy to use system for builders
website: https://buildsystem.eintosti.de
softdepend: [ LuckPerms, PlaceholderAPI, WorldEdit ]

commands:
  back:
    description: Teleports you to your previous location.
    usage: /<command>
  blocks:
    description: Opens a menu with secret blocks.
    usage: /<command>
  build:
    description: Puts you into "Build Mode".
    usage: /<command> [player]
  buildsystem:
    description: Overview of all plugin commands.
    usage: /<command>
  config:
    description: Reload the config.
    usage: /<command> reload
  explosions:
    description: Toggle explosions.
    usage: /<command> reload
  gamemode:
    aliases: [ gm ]
    description: Change your gamemode
    usage: /<command> <mode> [player]
  day:
    description: Set a world's time to daytime.
    usage: /<command> [world]
  night:
    description: Set a world's time to nighttime.
    usage: /<command> [world]
  noai:
    description: Disable all the entity AIs in a world.
    usage: /<command> [world]
  physics:
    description: Toggle block physics.
    usage: /<command> [world]
  settings:
    description: Manage user settings.
    usage: /<command>
  setup:
    description: Change the default items in GUIs.
    usage: /<command>
  skull:
    description: Receive a player's skull.
    usage: /<command> [name]
  spawn:
    description: Teleport to the spawn.
    usage: /<command>
  speed:
    aliases: [ s ]
    description: Change your flying/walking speed.
    usage: /<command> [1-5]
  top:
    description: Teleports you to the highest location.
    usage: /<command>
  worlds:
    aliases: [ w ]
    description: Open the world menu.
    usage: /<command>

permissions:
  buildsystem.navigator:
    description: Open the worlds navigator.
    default: true
  buildsystem.navigator.item:
    description: Receive and use the naviagtor open.
    default: true
  buildsystem.create.private:
    description: Create a private world.
    default: true
  buildsystem.create.type.normal:
    description: Create a normal world.
    default: true
  buildsystem.create.type.flat:
    description: Create a flat world.
    default: true
  buildsystem.create.type.nether:
    description: Create a nether world.
    default: true
  buildsystem.create.type.end:
    description: Create an end world.
    default: true
  buildsystem.create.type.void:
    description: Create a void world.
    default: true
  buildsystem.physics.message:
    description: Receive the message that physics are disabled in a world.
    default: true
  buildsystem.updates:
    description: Receive update messages.
    default: op